server:
  port: 8761

eureka:
  client:
    registerWithEureka: false                     #是否将自身注册到eureka中
    fetchRegistry: false                          #是否从Eureka服务中获取注册信息
    serverUrl:
      defaultZone: http://localhost:8761/eureka/  #设置与Eureka Server交互的地址,查询和注册都需要依赖这个地址,多个地址使用逗号分隔
